### ISSUE TITLE
Costs not showing up

### ISSUE THREAD

**Issue by TrapMusicJunkie** [badlydressedboy/azure-data-costs-ui#3]
Costs are not showing up. All other columns are fine.

Is Billing Administrator role enough to see the costs?

![image](https://github.com/badlydressedboy/azure-data-costs-ui/assets/78150989/5b5da6e3-7fa7-4748-8db3-20a8df91b9f2)

**Comment by badlydressedboy** [comment]
On the subscriptions tab did you select the costs check box for the
subscription?

**Comment by TrapMusicJunkie** [comment]
> On the subscriptions tab did you select the costs check box for the subscription?

Yes, Sir. Got everything checked:

![image](https://github.com/badlydressedboy/azure-data-costs-ui/assets/78150989/1dd18a18-56b2-48b8-b2b9-b0f7cbc3e022)

**Comment by badlydressedboy** [comment]
Did you download the exe or did you clone the code? If you have the code
you can put a breakpoint in the http call for the costs to see what is
wrong.
If you got the exe then you will have to wait for me to add code that
displays cost query errors. This might be end of day today or tomorrow.

As long as you can see costs in the portal you should be able to see them
in the tool. Presume you can see them in portal?

**Comment by TrapMusicJunkie** [comment]
I have downloaded the exe. I can see the costs in portal.

![image](https://github.com/badlydressedboy/azure-data-costs-ui/assets/78150989/5d95dcad-9303-4bb8-891e-4206179de606)

![image](https://github.com/badlydressedboy/azure-data-costs-ui/assets/78150989/b7f0bf7f-4850-494c-92fc-8fbbfd3b64fb)

**Comment by badlydressedboy** [comment]
Ok, I've got you covered, will add logging around costs queries, will let
you know when ready to download.

**Comment by badlydressedboy** [comment]
After costs dont load, do you get any messages on the subscriptions errors
column?

[image: image.png]

**Comment by TrapMusicJunkie** [comment]
No, all other columns are completely fine. No errors on the subscriptions column.

**Comment by TrapMusicJunkie** [comment]
Ahh sorry just noticed that I actually get some errors. I get "No expected DB costs found" error.

**Comment by badlydressedboy** [comment]
The "Too Many Requests" message is an indicator that requests are being throttled. This is why the subscriptions tab lets you select only a sunset of your subscriptions. Try only selecting 1 subscription to begin with and see if costs get picked up. If they do then experiment with how many subscriptions you can select before you get that error. It is all dependent on how many things you have in each subscription so there is no rule for everybody, just a little bit of experimentation.

**Comment by TrapMusicJunkie** [comment]
Tested while logged in via Azure CLI but have the same issue. Not sure if it is relevant but when I hit "Analyse spend" button "Over Provision%" column gets refreshed.

**Comment by badlydressedboy** [comment]
Grab the latest release and look in the info log which will be created on the logs folder, wherever the exe runs.
Look for:

- HTTP Header x-ms-ratelimit-remaining-subscription-reads: - this will tell you if azure if throttling your calls
- Complete GetSubscriptionCosts() for {your subscription name}; x costs found. - this will tell you if any costs were found. If 0 then maybe a permission issue, if > 0 then the costs are not mapping to your databases which may be something as trivial as capitalization of resource names. if so then easy fix. Let me know.

**Comment by TrapMusicJunkie** [comment]
Thank you for adding the logs. 

Looking at the info log I get the following errors:

2024-02-28 10:28:43.1772|INFO|Azure.Costs.Common.APIAccess.GetSubscriptionCosts|HTTP Header x-ms-ratelimit-remaining-subscription-reads: 
2024-02-28 10:28:43.1772|ERROR|Azure.Costs.Common.APIAccess.GetSubscriptionCosts|Couldnt get costs for subscription: {my_subscription_name}; Bad Request
2024-02-28 10:28:43.1772|INFO|Azure.Costs.Ui.Wpf.DataContextVM.RefreshDatabases(DataContextVM.cs:497)|No expected DB costs found for sub: {my_subscription_name}
2024-02-28 10:40:21.4903|ERROR|Azure.Costs.Ui.Wpf.DataContextVM.MapCostToDb(DataContextVM.cs:792)|elastic db!
2024-02-28 10:40:21.4903|INFO|Azure.Costs.Ui.Wpf.DataContextVM.MapCostToDb(DataContextVM.cs:823)|why no cost for DB db_name? Costs.count: 0
2024-02-28 10:40:21.4903|ERROR|Azure.Costs.Ui.Wpf.DataContextVM.MapCostToDb(DataContextVM.cs:792)|elastic db!
2024-02-28 10:40:21.4903|INFO|Azure.Costs.Ui.Wpf.DataContextVM.MapCostToDb(DataContextVM.cs:823)|why no cost for DB db_name? Costs.count: 0
2024-02-28 10:40:21.4903|ERROR|Azure.Costs.Ui.Wpf.DataContextVM.MapCostToDb(DataContextVM.cs:792)|elastic db!
2024-02-28 10:40:21.4903|INFO|Azure.Costs.Ui.Wpf.DataContextVM.MapCostToDb(DataContextVM.cs:823)|why no cost for DB db_name? Costs.count: 0
2024-02-28 10:40:21.4903|ERROR|Azure.Costs.Ui.Wpf.DataContextVM.MapCostToDb(DataContextVM.cs:792)|elastic db!
2024-02-28 10:40:21.4903|INFO|Azure.Costs.Ui.Wpf.DataContextVM.MapCostToDb(DataContextVM.cs:823)|why no cost for DB db_name? Costs.count: 0
2024-02-28 10:40:21.4903|ERROR|Azure.Costs.Ui.Wpf.DataContextVM.MapCostToDb(DataContextVM.cs:792)|elastic db!
2024-02-28 10:40:21.4903|INFO|Azure.Costs.Ui.Wpf.DataContextVM.MapCostToDb(DataContextVM.cs:823)|why no cost for DB db_name? Costs.count: 0
2024-02-28 10:40:21.4903|ERROR|Azure.Costs.Ui.Wpf.DataContextVM.MapCostToDb(DataContextVM.cs:792)|elastic db!
2024-02-28 10:40:21.4903|INFO|Azure.Costs.Ui.Wpf.DataContextVM.MapCostToDb(DataContextVM.cs:823)|why no cost for DB db_name? Costs.count: 0
2024-02-28 10:40:21.4903|ERROR|Azure.Costs.Ui.Wpf.DataContextVM.MapCostToDb(DataContextVM.cs:792)|elastic db!
2024-02-28 10:40:21.4903|INFO|Azure.Costs.Ui.Wpf.DataContextVM.MapCostToDb(DataContextVM.cs:823)|why no cost for DB db_name? Costs.count: 0
2024-02-28 10:40:21.4903|ERROR|Azure.Costs.Ui.Wpf.DataContextVM.MapCostToDb(DataContextVM.cs:792)|elastic db!
2024-02-28 10:40:21.4903|INFO|Azure.Costs.Ui.Wpf.DataContextVM.MapCostToDb(DataContextVM.cs:823)|why no cost for DB db_name? Costs.count: 0

(replaced original db names with "db_name").

Tried via Azure CLI with Billing Administrator role + Contributor role.

**Comment by badlydressedboy** [comment]
I will look into this and get back to you. The bad request is the point of
failure, something about what is being sent in the rest call is funky, I
will add logging to display the call content...

**Comment by badlydressedboy** [comment]
OK grab latest - it now logs 2 extra things on cost query failure:

- Request url: - https://management.azure.com/subscriptions/...etc is hard coded as the beginning of the url but Im not sure if this may be different if you are using a special azure domain like government/military etc. 
- Request content: - json representing the cost query. This should be the same for all users apart from to and from dates injected into the string, It will be interesting to see if your json has somehow got a whacky time format in it.

Let me know what you find. The problem and fix should be in plain sight now.

**Comment by TrapMusicJunkie** [comment]
OK. Checked the latest version and I get the following error:

_2024-02-29 11:44:40.3402|ERROR|Azure.Costs.Common.APIAccess.GetSubscriptionCosts|Couldnt get costs for subscription: {my_subscription_name}; Bad Request
2024-02-29 11:44:40.3440|ERROR|Azure.Costs.Common.APIAccess.GetSubscriptionCosts|Request url: https://management.azure.com/subscriptions/{my_subscription_id}/providers/Microsoft.CostManagement/query?api-version=2021-10-01
2024-02-29 11:44:40.3440|ERROR|Azure.Costs.Common.APIAccess.GetSubscriptionCosts|Request content: {"type":"ActualCost"
                   
                            ,"timeframe": "Custom"
                            , "timePeriod":{"from":"2024-01-30T10:44:38Z","to":"2024-02-29T10:44:38Z"}
                            ,"dataSet":{
                                "granularity":"None"
                                
 ,"filter": { 
                                    "dimensions": {
                                        "name": "serviceName"
                                        ,"operator": "In"
                                        ,"values": [  


                                            "Azure Data Factory v2"
                                            ,"SQL Database"
                                            ,"SQL Server"
                                            ,"Storage"
                                            ,"Virtual machines"
                                            ,"Bandwidth"
                                            ,"Virtual Network"
                                            ,"Advanced Threat Protection"
                                            ,"Purview"
                                            ,"Azure Purview"
                                            ,"Power BI Embedded"
                                            ,"Azure Synapse Analytics"
                                            ,"Synapse SQL Pool"
                                        ]
                                    }
                                }



                            ,"aggregation":{
                                "totalCost":{
                                    "name":"Cost"
                                    ,"function":"Sum"
                                },
                                "totalCostUSD":{
                                    "name":"CostUSD"
                                    ,"function":"Sum"
                                }
                            }
                            ,"sorting":[
                                {"direction":"descending"
                                ,"name":"Cost"}
                            ]
                            ,"grouping":[
                                {"type":"Dimension"
                                ,"name":"ResourceId"
                                }
                                ,{"type":"Dimension"
                                    ,"name":"ServiceName"
                                }
                                ,{"type":"Dimension"
                                    ,"name":"MeterSubCategory"
                                }
                                ,{"type":"Dimension"
                                    ,"name":"Product"
                                }
                                ,{"type":"Dimension"
                                    ,"name":"Meter"
                                }
                                ,{"type":"Dimension"
                                    ,"name":"ChargeType"
                                }
                                ,{"type":"Dimension"
                                    ,"name":"PublisherType"
                                }
                                ,{"type":"Dimension"
                                    ,"name":"Provider"
                                }
                               
                                ,{"type":"Dimension"
                                    ,"name":"MeterCategory"
                                }
                                ,{"type":"Dimension"
                                    ,"name":"ResourceType"
                                }
                            ]
                        }
                    }
2024-02-29 11:44:40.3440|ERROR|Azure.Costs.Ui.Wpf.DataContextVM.MapCostToDb(DataContextVM.cs:792)|elastic db!
2024-02-29 11:44:40.3440|ERROR|Azure.Costs.Ui.Wpf.DataContextVM.MapCostToDb(DataContextVM.cs:792)|elastic db!
2024-02-29 11:44:40.3440|ERROR|Azure.Costs.Ui.Wpf.DataContextVM.MapCostToDb(DataContextVM.cs:792)|elastic db!
2024-02-29 11:44:40.3440|ERROR|Azure.Costs.Ui.Wpf.DataContextVM.MapCostToDb(DataContextVM.cs:792)|elastic db!
2024-02-29 11:44:40.3440|ERROR|Azure.Costs.Ui.Wpf.DataContextVM.MapCostToDb(DataContextVM.cs:792)|elastic db!
2024-02-29 11:44:40.3440|ERROR|Azure.Costs.Ui.Wpf.DataContextVM.MapCostToDb(DataContextVM.cs:792)|elastic db!
2024-02-29 11:44:40.3440|ERROR|Azure.Costs.Ui.Wpf.DataContextVM.MapCostToDb(DataContextVM.cs:792)|elastic db!
2024-02-29 11:44:40.3440|ERROR|Azure.Costs.Ui.Wpf.DataContextVM.MapCostToDb(DataContextVM.cs:792)|elastic db!_

**Comment by TrapMusicJunkie** [comment]
Here is the error detail:

2024-03-01 11:09:15.6833|ERROR|Azure.Costs.Common.APIAccess.GetSubscriptionCosts|Response text: {"error":{"code":"BadRequest","message":"Invalid query definition, Dataset is invalid or not supplied. (Request ID: ID_HERE)"}}
2024-03-01 11:09:15.6833|ERROR|Azure.Costs.Common.APIAccess.GetSubscriptionCosts|Use the above token, url and content to test in postman (set authorization: bearer token & paste token in, url is a POST and paste content into body as raw)

So I also tried to use postman and I got the same error

    "error": {
        "code": "BadRequest",
        "message": "Invalid query definition, Dataset is invalid or not supplied. (Request ID: d13cf81e-6dff-4a84-b046-01ee60c6f14f)"
    }
}

**Comment by badlydressedboy** [comment]
Did you have to modify the default postman headers to get it to that point? It should have errored out with a content type error unless you changed the headers.

Can you run your json request content through this free tool:
https://www.atatus.com/tools/json-lint

If it is valid json take the formatted version on the right and try it in postman again.

**Comment by TrapMusicJunkie** [comment]
I did not modify postman headers. Just copied and pasted url, token and body.

> Can you run your json request content through this free tool:
> https://www.atatus.com/tools/json-lint

Basically, I have pasted the request content from error log and got some weird output. Not sure if I am doing it correctly?

![image](https://github.com/badlydressedboy/azure-data-costs-ui/assets/78150989/ae3cebb9-32a5-4662-85d0-b76e8c52cc4f)

**Comment by badlydressedboy** [comment]
If you get rid of the first 2 {{ does it work?

**Comment by TrapMusicJunkie** [comment]
No, I get the following output:

```
Parse error on line 2:
...: "ActualCost",    ,    ,    "timefra
----------------------^
Expecting 'STRING', got ',', 
```

**Comment by badlydressedboy** [comment]
How did you get json that starts with 3 { ? Your json you posted in the comment 7 above this one, start with a single {. If you use the json you posted above, does it work?

**Comment by TrapMusicJunkie** [comment]
You are right. The fresh one generated today starts with 3 {

![image](https://github.com/badlydressedboy/azure-data-costs-ui/assets/78150989/533b26ec-b553-4f29-b800-645623a9c012)

Once I entered the old one (with a single { )posted in my earlier post it seems like it got validated:

![image](https://github.com/badlydressedboy/azure-data-costs-ui/assets/78150989/e10cfa27-56a2-4a45-aa99-c570c04ae123)

**Comment by badlydressedboy** [comment]
Please download latest release - it gets rids of the 3 { bug, which should give you valid json and potentially a successful result in postman.

**Comment by badlydressedboy** [comment]
I have removed product and provider fields from the query so the error above should be fixed. Grab latest and let me know.

**Comment by TrapMusicJunkie** [comment]
From the other hand when I check postman I can see that it tries to fetch the costs:

![image](https://github.com/badlydressedboy/azure-data-costs-ui/assets/78150989/24a67e7d-e3cd-4db2-a9f8-11ad80f4db77)

**Comment by TrapMusicJunkie** [comment]
I am located in Poland. We use , as a decimal:

![image](https://github.com/badlydressedboy/azure-data-costs-ui/assets/78150989/dc1d9516-12ee-42ca-aad1-12b8aceee960)

**Comment by badlydressedboy** [comment]
OK makes sense now. I have added code to accept , as well as ..
Pls grab latest...

**Comment by TrapMusicJunkie** [comment]
Seems like we have a success here 🥇 

Thank you very much for your patience and time on this! Really appreciated 👍 

Will have few more questions but I will post them in the discussions section.

**Comment by badlydressedboy** [comment]
AWESOME! That was painful but really happy it paid off, thanks also for sticking with it!

Learnings:

- The management.azure.com/your_resource_url/query? endpoint allows different groupings/dimensions (fails if disallowed grouping given) for different users even if the api version is the same. This is highly annoying, I have no idea why this is.
- The above API also always returns costs with '.' decimal places regardless of your locale, I suppose there is no header specifying locale so makes sense. '.' always need to be converted to local separator.

**Comment by TrapMusicJunkie** [comment]
In this case I will close this issue. Thanks!
