### ISSUE TITLE
Costs for disks for VMs not visible

### ISSUE THREAD

**Issue by Azure365Addict** [badlydressedboy/azure-data-costs-ui#6]
Costs for disks added to VMs are not visible. I would expect to see them.

Example based on XXXXXC01 VM which has two additional data disks:

Costs in app:

![image](https://github.com/badlydressedboy/azure-data-costs-ui/assets/78150989/452a809c-af08-4ab3-aed4-fa27bde43be5)

Disks added to XXXXXC01 VM:

![image](https://github.com/badlydressedboy/azure-data-costs-ui/assets/78150989/d7905b16-baa0-4539-920a-2d8547413b85)

Actual cost of XXXXXC01 disks:

![image](https://github.com/badlydressedboy/azure-data-costs-ui/assets/78150989/f9463ae1-9e08-457e-88c1-089d2453610d)
![image](https://github.com/badlydressedboy/azure-data-costs-ui/assets/78150989/46e71a2a-cc98-4e06-b299-57fb52b87f70)

**Comment by badlydressedboy** [comment]
I just released a new version with vm disks. Im not sure the az portal actually gives this view and vm and data disk costs together so I hope it offers a convenience for people who might like this.

**Comment by TrapMusicJunkie** [comment]
You are a star 🥇 

Thank you!
